
server.port=${PORT:8086}

kaffe.datasource.url=${DB_URL:${DATABASE_URL}}
kaffe.datasource.username=${DB_USERNAME:${DB_USER:postgres}}
kaffe.datasource.password=${DB_PASSWORD}
kaffe.datasource.driver-class-name=org.postgresql.Driver

kaffe.jwt.secret=${JWT_SECRET}
kaffe.jwt.cookie-name=${JWT_COOKIE_NAME:KAFFE_AUTH}

kaffe.auth.schema=${KAFFE_AUTH_SCHEMA:kaffe_auth}
