begin;

create schema if not exists menu;

create table if not exists menu.menus
(
    menu_id       bigint generated by default as identity primary key,
    tenant_id     bigint not null references core.tenants (tenant_id) on delete cascade,
    name          varchar(120) not null,
    description   text,
    is_global     boolean not null default true,
    is_active     boolean not null default true,
    sort_order    integer not null default 0,
    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now(),
    deleted_at    timestamp with time zone,
    deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null
);

create unique index if not exists uq_menu_menus_tenant_name_active
    on menu.menus (tenant_id, lower(name))
    where deleted_at is null;

create index if not exists idx_menu_menus_tenant
    on menu.menus (tenant_id, is_active, sort_order)
    where deleted_at is null;

create table if not exists menu.menu_locations
(
    menu_id       bigint not null,
    tenant_id     bigint not null,
    location_id   bigint not null,
    is_active     boolean not null default true,
    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now(),
    deleted_at    timestamp with time zone,
    deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null,
    primary key (menu_id, location_id),
    foreign key (menu_id) references menu.menus (menu_id) on delete cascade,
    foreign key (location_id, tenant_id) references core.locations (location_id, tenant_id) on delete cascade
);

create index if not exists idx_menu_menu_locations_location
    on menu.menu_locations (location_id, is_active)
    where deleted_at is null;

create table if not exists menu.menu_categories
(
    menu_id       bigint not null,
    tenant_id     bigint not null,
    category_id   bigint not null,
    sort_order    integer not null default 0,
    is_active     boolean not null default true,
    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now(),
    deleted_at    timestamp with time zone,
    deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null,
    primary key (menu_id, category_id),
    foreign key (menu_id) references menu.menus (menu_id) on delete cascade,
    foreign key (category_id, tenant_id) references menu.categories (category_id, tenant_id) on delete cascade
);

create index if not exists idx_menu_menu_categories_category
    on menu.menu_categories (category_id, is_active)
    where deleted_at is null;

alter table menu.categories
    add column if not exists deleted_at timestamp with time zone,
    add column if not exists deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null;

alter table menu.products
    add column if not exists deleted_at timestamp with time zone,
    add column if not exists deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null;

alter table menu.lkp_addon_groups
    add column if not exists deleted_at timestamp with time zone,
    add column if not exists deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null;

alter table menu.lkp_addons
    add column if not exists deleted_at timestamp with time zone,
    add column if not exists deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null;

alter table menu.location_products
    add column if not exists deleted_at timestamp with time zone,
    add column if not exists deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null;

alter table menu.location_addons
    add column if not exists deleted_at timestamp with time zone,
    add column if not exists deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null;

alter table menu.product_addon_groups
    add column if not exists deleted_at timestamp with time zone,
    add column if not exists deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null,
    add column if not exists is_required boolean,
    add column if not exists min_selection integer,
    add column if not exists max_selection integer;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'chk_product_addon_groups_selection'
          and conrelid = 'menu.product_addon_groups'::regclass
    ) then
        alter table menu.product_addon_groups
            add constraint chk_product_addon_groups_selection
            check (
                (min_selection is null or min_selection >= 0)
                and (max_selection is null or max_selection >= coalesce(min_selection, 0))
            ) not valid;
    end if;
end $$;

create index if not exists idx_menu_categories_active
    on menu.categories (tenant_id, is_active, sort_order)
    where deleted_at is null;

create index if not exists idx_menu_products_active
    on menu.products (tenant_id, category_id, is_available, sort_order)
    where deleted_at is null;

create index if not exists idx_menu_addon_groups_active
    on menu.lkp_addon_groups (tenant_id, is_active, sort_order)
    where deleted_at is null;

create index if not exists idx_menu_addons_active
    on menu.lkp_addons (tenant_id, addon_group_id, is_active, sort_order)
    where deleted_at is null;

create index if not exists idx_menu_location_products_active
    on menu.location_products (tenant_id, location_id, is_available, sort_order)
    where deleted_at is null;

commit;
