alter table menu.products
    add column if not exists image_asset_id uuid references media.assets (asset_id) on delete set null;

create index if not exists idx_menu_products_image_asset
    on menu.products (image_asset_id)
    where image_asset_id is not null;

comment on column menu.products.image_asset_id is
    'Optional reference to media.assets for the canonical product image uploaded through presigned S3 flow.';

create table if not exists menu.product_images
(
    product_image_id bigint generated by default as identity primary key,
    tenant_id        bigint not null,
    product_id       bigint not null,
    asset_id         uuid references media.assets (asset_id) on delete set null,
    image_url        text not null,
    alt_text         varchar(160),
    caption          varchar(180),
    sort_order       integer not null default 0,
    is_primary       boolean not null default false,
    is_visible       boolean not null default true,
    created_at       timestamp with time zone not null default now(),
    updated_at       timestamp with time zone not null default now(),
    deleted_at       timestamp with time zone,
    deleted_by_user_id bigint references kaffe_auth.users (user_id) on delete set null,
    constraint product_images_product_tenant_fk
        foreign key (product_id, tenant_id) references menu.products (product_id, tenant_id) on delete cascade
);

create index if not exists idx_menu_product_images_product
    on menu.product_images (tenant_id, product_id, is_visible, sort_order)
    where deleted_at is null;

create index if not exists idx_menu_product_images_asset
    on menu.product_images (asset_id)
    where asset_id is not null;

create unique index if not exists uq_menu_product_images_primary
    on menu.product_images (tenant_id, product_id)
    where is_primary = true and deleted_at is null;

comment on table menu.product_images is
    'Gallery of images for each menu product. One active image can be primary; products.image_url/image_asset_id mirror that primary image for compatibility.';
